# This is a basic workflow to help you get started with Actions

name: GitHub Actions Demo
workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true

